---
kind: pipeline
type: docker
name: mouse-amd64

platform:
  arch: amd64

steps:
  - name: test
    image: rust:1.73
    commands:
      - cargo test
  - name: compile
    image: rust:1.73
    commands:
      - cargo build --target x86_64-unknown-linux-gnu


---
kind: pipeline
type: docker
name: mouse-arm64

platform:
  arch: arm64

steps:
  - name: test
    image: rust:1.73
    commands:
      - cargo test
  - name: compile
    image: rust:1.73
    commands:
      - cargo build --target aarch64-unknown-linux-gnu
  - name: 
    image: rust:1.73
    environment:
      TOKEN:
        from_secret: gitea_token
    commands:
      - cargo publish --registry gita --token $TOKEN

